set x=wscript.createobject ("wscript.shell")
do
wscript.sleep 100
x.sendkeys "{CAPSLOCK}"
x.sendkeys "{NUMLOCK}"
x.sendkeys "You cant escape DedSec "
x.sendkeys "{SCROLLLOCK}"
loop
Wshshell.run "Notepad"
wscript.sleep 100
wshshell.sendkeys "T"
wscript.sleep 100
wshshell.sendkeys "H"
wscript.sleep 100
wshshell.sendkeys "I"
wscript.sleep 100
wshshell.sendkeys "S"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "I"
wscript.sleep 100
wshshell.sendkeys "S"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "D"
wscript.sleep 100
wshshell.sendkeys "E"
wscript.sleep 100
wshshell.sendkeys "D"
wscript.sleep 100
wshshell.sendkeys "S"
wscript.sleep 100
wshshell.sendkeys "E"
wscript.sleep 100
wshshell.sendkeys "C"